# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'twrnc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # Pods for twrnc

  target 'twrncTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
